### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by yhwang-hub** [Tartisan/MMDet3d-CenterPoint#3]
我在转onnx的时候报错：
Traceback (most recent call last):
  File "centerpoint_deploy/export_onnx.py", line 371, in <module>
    main()
  File "centerpoint_deploy/export_onnx.py", line 336, in main
    pts_voxel_encoder = build_pfn_model(cfg, args.checkpoint, device=device)
  File "centerpoint_deploy/export_onnx.py", line 258, in build_pfn_model
    in_channels=cfg.model['pts_voxel_encoder']['in_channels'],
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/config.py", line 38, in __missing__
    raise KeyError(name)
KeyError: 'in_channels'
请问这个是什么原因？该如何修改？
运行命令：
python centerpoint_deploy/export_onnx.py demo/data/kitti/kitti_000008.bin configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py checkpoints/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.pth

**Comment by Tartisan** [comment]
There's no "in_channels" in `pts_voxel_encoder` layer, the voxel version of CenterPoint is not supported in this code, you need to adapt it according to your model
