### ISSUE TITLE
load pcd file error

### ISSUE THREAD

**Issue by yhwang-hub** [Tartisan/MMDet3d-CenterPoint#4]
```
Traceback (most recent call last):
  File "centerpoint_deploy/export_onnx.py", line 373, in <module>
    main()
  File "centerpoint_deploy/export_onnx.py", line 353, in main
    data = load_data(model, args.pcd)
  File "centerpoint_deploy/export_onnx.py", line 245, in load_data
    data = test_pipeline(data)
  File "/home/wyh/mmdetection3d/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "/home/wyh/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 431, in __call__
    points = self._load_points(pts_filename)
  File "/home/wyh/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 408, in _load_points
    points = np.frombuffer(pts_bytes, dtype=np.float32)
ValueError: buffer size must be a multiple of element size
```

run command：
`python centerpoint_deploy/export_onnx.py /home/wyh/mmdetection3d/demo/data/kitti/000060.pcd configs/centerpoint/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus.py checkpoints/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus.pth`

**Comment by Tartisan** [comment]
mmdet3d doesn't support .pcd file as far as I know, change a bin file instead
